name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: submissions_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables for testing
        run: |
          cat > .env << EOL
          APP_NAME=PAMP Submissions Service Test
          APP_VERSION=1.0.0-test
          DEBUG=true
          DATABASE_URL=postgresql://postgres:password@localhost:5432/submissions_db_test
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=password
          POSTGRES_DB=submissions_db_test
          POSTGRES_HOST=localhost
          POSTGRES_PORT=5432
          EOL

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run tests
        run: |
          # Run pytest with coverage
          python -m pytest -v --tb=short
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/submissions_db_test 